CONST_FILL_PRICE_CHANGE = 0.05
CONST_DIRECTION_SELL = 0
CONST_DIRECTION_BUY = 1
CONST_DIRECTION_HALF = 2
CONST_FILL_PRICE_ZERO = 0
CONST_FILL_VOLUME_CHANGE = 0.01
CONST_FILL_VOLUME_ZERO = 0
CONST_INITIAL_VOLUME_NUMBER_ROUNDING = 1
SUCCESS_CONNECTED = "Successfully connected..."
FAILED_CONNECTION = "Failed connection to DB"
CREATE_SQL_QUERY = "Requests successfully created"
ERROR_CREATE_SQL_QUERY = "Error creating requests"
SUCCESSFULLY_GENERATE_DATA = "Data successfully generated"
ERROR_GENERATE_DATA = "Error in data generation"
TIME_LIMIT = "Time limit successfully generated"
ERROR_TIME_LIMIT = "Error in generating time limits"
SUCCESS_ROWS_WITHOUT_REPEAT = "All rows with repetitions were successfully generated"
ERROR_ROWS_WITHOUT_REPEAT = "Error generating rows with duplicate values"
LOGING_SETUP = "Loging was set up"
ADDITIONAL_TABLE_SUCCESS = "Intermediate table without repetition successfully created"
ADDITIONAL_TABLE_ERROR = "Error in creating an intermediate table without repetitions"
DIFFERENCE_DATE_INFO = "Difference between dates calculated correctly"
